apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-2pkl
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-2pkl
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-2pkl
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-2pkl
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-2pkl
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-fhnx-tenant/rhtap-demo-app/hacbs-test-project-2pkl@sha256:f3ea7313392e00045b009fdf5bc8a7c7b9b1df5ffe9fe4f537c0e2b2f7746519
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
